title: React Native Whirlwind ðŸŒªï¸
email: andre.rabold@gmail.com
description: >-
  Whirlwind is a utility-first CSS framework designed for React Native. It is 
  heavily inspired by Tachyons and Tailwind CSS and uses low-level building 
  blocks for rapidly building custom designs.
baseurl: '' # the subpath of your site, e.g. /blog
url: '' # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: AndroidJunky
github_username: arabold

# Build settings
# theme: minima
remote_theme: pmarsceill/just-the-docs

header_pages:
  - index.md
  - getting-started.md
  - Background
  - background/background-color.md
  - Borders
  - borders/border-color.md
  - borders/border-radius.md
  - borders/border-width.md
# plugins:
#   - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
